import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="navbar">
          <a href="/">Home</a>
          <a href="/users">Users </a>
          <a href="/games">Games </a>
          <a href="/consoles">Consoles </a>
          <a href="/genres">Game Genres</a>
        </nav>
        {children}
      </body>
    </html>
  );
}
